{
  pkgs,
  inputs,
  ...
}:
{
  home.packages = with pkgs; [
    segoe-ui
    fontpreview
    nerd-fonts.terminess-ttf
    maple-mono.truetype
    corefonts
    vista-fonts
    noto-fonts
    inputs.apple-fonts.packages.${pkgs.stdenv.hostPlatform.system}.sf-pro
    inputs.apple-fonts.packages.${pkgs.stdenv.hostPlatform.system}.sf-mono
    inputs.apple-fonts.packages.${pkgs.stdenv.hostPlatform.system}.ny
  ];
}
