hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("HYPRSHOT_DIR", "screenshots")
hl.env("NIXOS_OZONE_WL", "1")
hl.env("WLR_NO_HARDWARE_CURSORS", "1")
