#!/usr/bin/env bash

set -euo pipefail

STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}"
STATE_FILE="$STATE_DIR/hyprland-monitor-profile"
mkdir -p "$STATE_DIR"

assign_workspaces() {
    local left="DP-1"
    local right="HDMI-A-1"

    for ws in 2 4 6 8 10; do
        hyprctl dispatch moveworkspacetomonitor "$ws" "$left"
    done

    for ws in 1 3 5 7 9; do
        hyprctl dispatch moveworkspacetomonitor "$ws" "$right"
    done

}

apply_profile() {
    local profile=$1
    case "$profile" in
        "profile1")
            hyprctl keyword "monitor" "DP-1,disable"
            hyprctl keyword "monitor" "HDMI-A-1,disable"
            hyprctl keyword "monitor" "DP-1,2560x1440@120,0x0,1"
            hyprctl keyword "monitor" "HDMI-A-1,2560x1440@120,2560x0,1"
            assign_workspaces
            ;;
        "profile2")
            hyprctl keyword "monitor" "DP-1,disable"
            hyprctl keyword "monitor" "HDMI-A-1,2560x1440@120,0x0,1"
            ;;
        "profile3")
            hyprctl keyword "monitor" "HDMI-A-1,disable"
            hyprctl keyword "monitor" "DP-1,2560x1440@120,0x0,1"
            ;;
        "profile4")
            hyprctl keyword "monitor" "HDMI-A-1,disable"
            hyprctl keyword "monitor" "DP-1,5120x1440@144,0x0,1"
            ;;
        *)
            echo "[error] unknown profile: $profile"
            return 1
            ;;
    esac
}

if [ $# -eq 0 ]; then
    if [ -f "$STATE_FILE" ]; then
        profile=$(cat "$STATE_FILE")
        apply_profile "$profile"
    else
        apply_profile "profile1"
        echo "profile1" > "$STATE_FILE"
        hyprctl dispatch workspace 1
        systemctl restart --user hyprpaper.service
        systemctl restart --user waybar.service
    fi
else
    apply_profile "$1"
    echo "$1" > "$STATE_FILE"
fi

