#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
options=("DP-1|HDMI-A-1:2560x1440@120" "HDMI-A-1:2560x1440@120" "DP-1:2560x1440@120" "DP-1:5120x1440@144")
selected=$(printf "%s\n" "${options[@]}" | rofi -dmenu -p "DISPLAY PROFILES" -no-custom)

case "$selected" in
    "${options[0]}")
        "$SCRIPT_DIR/monitor-config" "profile1"
        ;;
    "${options[1]}")
        "$SCRIPT_DIR/monitor-config" "profile2"
        ;;
    "${options[2]}")
        "$SCRIPT_DIR/monitor-config" "profile3"
        ;;
    "${options[3]}")
        "$SCRIPT_DIR/monitor-config" "profile4"
        ;;
    *)
        exit 0
        ;;
esac
