set-option -g terminal-overrides ',xterm-256color:Tc'
set-option -g set-titles on
set-option -g set-titles-string "#S:#W"
set -g set-clipboard on
set -g pane-base-index 1
set -g status on
set -g status-interval 1
set -g status-left-length 100
set -g status-right-length 100
set -g status-position bottom
set -g status-style "fg=red,bg=#101010"
set -g status-left '#{tmux_mode_indicator}#[bg=green]#[fg=black] #S #[fg=#{@LGRAY} #[bg=magenta]#[fg=black]'
set -g status-right '#[fg=green]%Y-%m-%d #[fg=#ffffff]%H:%M'
set -g status-justify absolute-centre
set -g @mode_indicator_prefix_prompt ' WAIT '
set -g @mode_indicator_copy_prompt ' COPY '
set -g @mode_indicator_sync_prompt ' SYNC '
set -g @mode_indicator_empty_prompt ' NORM '
set -g @mode_indicator_prefix_mode_style 'bg=red,fg=black'
set -g @mode_indicator_copy_mode_style 'bg=#d9ba73,fg=black'
set -g @mode_indicator_sync_mode_style 'bg=red,fg=black'
set -g @mode_indicator_empty_mode_style 'bg=#272727,fg=#777777'
set -g @prefix_highlight_output_prefix "#[fg=#252530]#[bg=#d9ba73]"
set -g @prefix_highlight_output_suffix ""
setw -g window-status-separator " - "
setw -g window-status-format "#[fg=#777777,bg=#272727] #I #[fg=#777777,bg=black] #W "
setw -g window-status-current-format "#[fg=black,bg=red] #I #[fg=#ffffff,bg=black] #W "
bind-key "W" choose-window
bind-key "S" choose-session
bind-key "w" run-shell -b "~/.config/tmux/plugins/tmux-fzf/scripts/window.sh switch"
bind-key "s" run-shell -b "~/.config/tmux/plugins/tmux-fzf/scripts/session.sh switch"

# Reset all keybindings
unbind-key -a
bind ^X lock-server
bind ^C new-window -c "$HOME"
bind ^D detach
bind H previous-window
bind L next-window
bind r command-prompt "rename-window %%"
bind R source-file ~/.config/tmux/tmux.conf
bind ^A last-window
bind ^W list-windows
bind w list-windows
bind z resize-pane -Z
bind l refresh-client
bind "'" split-window -v
bind _ split-window -h
bind s split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind '"' choose-window
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind-key -n C-M-h select-pane -L
bind-key -n C-M-j select-pane -D
bind-key -n C-M-k select-pane -U
bind-key -n C-M-l select-pane -R
bind : command-prompt
bind * setw synchronize-panes
bind P set pane-border-status
bind c kill-pane
bind x swap-pane -D
bind S choose-session
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind Enter copy-mode
bind-key -n ^space copy-mode

