#!/usr/bin/bash

url=$(playerctl metadata mpris:artUrl)
artist=$(playerctl metadata xesam:artist)
album=$(playerctl metadata xesam:album)
metadata=$(printf "$artist - $album")

if [ $url == "No player found" ]
then
  exit
elif [ -f /tmp/"$metadata".png ]
then
  echo /tmp/"$metadata".png
else
  echo $url
  curl -s $url -o /tmp/"$metadata"
  gm convert /tmp/"$metadata" /tmp/"$metadata".png
  rm /tmp/"$metadata"
  echo /tmp/"$metadata".png
fi
