#!/usr/bin/bash

set -euo pipefail

FORCE=0

while getopts ":f" opt; do
    case "$opt" in
        f) FORCE=1 ;;
    esac
done

WALLPAPER_DIR="$HOME/.config/hypr/wallpaper/"
STATE_DIR="$HOME/.local/state/wallpaper"
STATE_FILE="$STATE_DIR/current"

mkdir -p $STATE_DIR

if echo $(hyprctl monitors -j | jq '.[0].availableModes') | grep 5120; then
    WALLPAPER_DIR="${WALLPAPER_DIR}ultrawide"
fi;

if [[ -f "$STATE_FILE" && $FORCE -eq 0 ]]; then
    NEXT_WALLPAPER="$(cat "$STATE_FILE")"
else
    CURRENT_WALLPAPER=$(awww query | sed -n 's/.*image: //p' | sed 's#.*/##')
    NEXT_WALLPAPER_FILE=$(ls "$WALLPAPER_DIR" | grep -vxF "$CURRENT_WALLPAPER" | shuf -n1)
    NEXT_WALLPAPER="$WALLPAPER_DIR/$NEXT_WALLPAPER_FILE"
fi


[[ -z "$NEXT_WALLPAPER" ]] && NEXT_WALLPER="$CURRENT_WALLPAPER"
echo "$NEXT_WALLPAPER" > "$STATE_FILE"

awww-daemon >/dev/null 2>&1 || sleep 0.1
awww img "$NEXT_WALLPAPER" --transition-type simple --transition-step 1 --transition-fps 100
