#!/usr/bin/bash

function setres {
        if echo $(hyprctl monitors -j | jq '.[0].availableModes') | grep 5120; then
		hyprctl keyword monitor "DP-1,5120x1440@144,auto,auto"
		hyprctl keyword workspace "w[t1], gapsout:1 2561 1 1"
	else
		hyprctl keyword monitor "DP-1,2560x1440@120,auto,auto"
		hyprctl keyword workspace "w[t1], gapsout:1"
        fi
}

# Hyprland sends monitor events for each connected monitor
# on start, but in case we start listening to the socket after
# these initial events were emitted, we need to explicitly set 
# the resolution.
setres

SOCK="$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock"
socat -u UNIX-CONNECT:$SOCK - | while read -r line; do
    echo "$line"
    if [[ "$line" == *"monitor"* ]] || [[ "$line" == *"configreloaded"* ]]; then
	    setres
    fi
done

